### ISSUE TITLE
ordered_load does not error on duplicate keys (can impact pre-commit usage)

### ISSUE THREAD

**Issue by sirosen** [asottile/aspy.yaml#34]
After reading this lib to see if what I'm looking for is reasonable, I _think_ it is, but admit to not being certain. I don't have enough background with pyyaml to be sure.

`ordered_load` would ideally have an option to error when loading a duplicate key. This lets calling libraries (most notably pre-commit) treat these as errors or at least warnings.

Consider the following malformed `.pre-commit-config.yaml` file:
```yaml
repos:
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
repos:  # DUPLICATE KEY!
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies: ['flake8-bugbear==19.3.0']
```

when loaded by pre-commit via `ordered_load`, it would be nice if this either failed, or at least produced a warning of some kind.

The current behavior is "last one wins" so you would see the `flake8` hook above, but not the `black` one.
